---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-terraform-provider-ec-acceptance
  description: Buildkite Pipeline for terraform-provider-ec acceptance tests
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/terraform-provider-ec

spec:
  type: buildkite-pipeline
  owner: group:control-plane-stateful
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: terraform-provider-ec-acceptance
    spec:
      repository: elastic/terraform-provider-ec
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        control-plane-stateful:
          access_level: MANAGE_BUILD_AND_READ
        cloud-applications-es:
          access_level: MANAGE_BUILD_AND_READ
        cloud-applications-solutions:
          access_level: MANAGE_BUILD_AND_READ
        platform-writers:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
