---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-terraform-provider-ec
  description: Buildkite Pipeline for terraform-provider-ec
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/terraform-provider-ec

spec:
  type: buildkite-pipeline
  owner: group:control-plane-stateful
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: terraform-provider-ec
    spec:
      repository: elastic/terraform-provider-ec
      pipeline_file: ".buildkite/pipeline.yml"
