"""Unit tests for check-pr-state.py.

Tests are designed to run without network or `gh` installed: they call the
pure `compute_payload()` function directly with hand-crafted fixture data.
A small handful of integration-shaped tests also exercise the resilience
and main() pathways using monkeypatched gh wrappers.

Run with:

    python -m pytest .agents/skills/pr-monitoring-loop/scripts/tests
"""

from __future__ import annotations

import importlib.util
import io
import json
import sys
from contextlib import redirect_stdout
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest


SCRIPT = Path(__file__).resolve().parent.parent / "check-pr-state.py"


@pytest.fixture(scope="session")
def cps():
    spec = importlib.util.spec_from_file_location("check_pr_state", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------


HEAD_SHA = "headsha1234567890"
OLD_SHA = "oldsha000000000000"


def _pr(head_sha=HEAD_SHA, **overrides):
    base = {
        "number": 42,
        "url": "https://example.test/pulls/42",
        "state": "OPEN",
        "isDraft": False,
        "headRefName": "feature/x",
        "headRefOid": head_sha,
        "baseRefName": "main",
        "baseRefOid": "basesha",
        "reviewDecision": "REVIEW_REQUIRED",
        "mergeable": "MERGEABLE",
        "mergeStateStatus": "CLEAN",
        "labels": [],
        "statusCheckRollup": [],
        "title": "test PR",
        "updatedAt": "2026-05-07T00:00:00Z",
        "author": {"login": "human-dev"},
    }
    base.update(overrides)
    return base


def _comment(cid, login, body="hi", created="2026-05-07T01:00:00Z"):
    return {
        "id": cid,
        "user": {"login": login, "type": "Bot" if login.endswith("[bot]") else "User"},
        "body": body,
        "created_at": created,
        "updated_at": created,
    }


def _review_comment(cid, login, body="line note", created="2026-05-07T01:00:00Z"):
    return {
        "id": cid,
        "user": {"login": login, "type": "Bot" if login.endswith("[bot]") else "User"},
        "body": body,
        "path": "src/foo.go",
        "created_at": created,
        "updated_at": created,
    }


def _review(rid, login, state, commit_id=HEAD_SHA, submitted="2026-05-07T01:00:00Z", body=""):
    return {
        "id": rid,
        "user": {"login": login, "type": "Bot" if login.endswith("[bot]") else "User"},
        "state": state,
        "commit_id": commit_id,
        "submitted_at": submitted,
        "body": body,
    }


VERIFY_REPORT_BODY = (
    "## Verification Report: `some-change`\n\n"
    "Generated by OpenSpec verify (label) for issue #42"
)


def _verify_review(rid, state, commit_id=HEAD_SHA, submitted="2026-05-07T01:05:00Z"):
    """A review posted by the verify-openspec workflow (runs as github-actions[bot])."""
    return _review(
        rid,
        "github-actions[bot]",
        state,
        commit_id=commit_id,
        submitted=submitted,
        body=VERIFY_REPORT_BODY,
    )


def _label_event(action, at, label_name="verify-openspec"):
    return {
        "event": action,
        "created_at": at,
        "label": {"name": label_name},
    }


def _thread(tid, comments, resolved=False, outdated=False):
    return {
        "id": tid,
        "isResolved": resolved,
        "isOutdated": outdated,
        "path": "src/foo.go",
        "line": 1,
        "originalLine": 1,
        "comments": {"nodes": comments},
    }


def _thread_comment(node_id, db_id, login, created="2026-05-07T01:00:00Z"):
    return {
        "id": node_id,
        "databaseId": db_id,
        "author": {"login": login},
        "body": "please change",
        "createdAt": created,
        "updatedAt": created,
        "diffHunk": "@@",
        "path": "src/foo.go",
        "line": 1,
        "originalLine": 1,
        "outdated": False,
        "url": "https://example.test/c",
    }


def _empty_kwargs():
    return dict(
        repo={"owner": "o", "name": "r"},
        pr=_pr(),
        pr_check_data=[],
        commit_check_run_data=[],
        commit_status_data={},
        review_data=[],
        issue_comment_data=[],
        review_comment_data=[],
        thread_data=[],
        event_data=[],
        merge_conflict_data={"hasConflicts": False, "files": [], "analysisAvailable": True},
        state={},
    )


# ---------------------------------------------------------------------------
# new-since semantics (incl. bots are first-class)
# ---------------------------------------------------------------------------


def test_first_run_no_state_treats_all_comments_as_new(cps):
    kwargs = _empty_kwargs()
    kwargs["issue_comment_data"] = [
        _comment(1, "human-dev"),
        _comment(2, "macroscope[bot]"),
    ]
    kwargs["review_comment_data"] = [_review_comment(10, "verify-openspec[bot]")]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["comments"]["newIssueComments"] == 2
    assert payload["summary"]["comments"]["newReviewComments"] == 1
    assert "issue_comments" in payload["summary"]["actionable"]
    assert "review_comments" in payload["summary"]["actionable"]


def test_seen_ids_silence_known_comments_and_bot_comments(cps):
    kwargs = _empty_kwargs()
    kwargs["issue_comment_data"] = [
        _comment(1, "human-dev"),
        _comment(2, "verify-openspec[bot]"),
    ]
    kwargs["state"] = {
        "seenIssueCommentIds": [1, 2],
        "lastPolledAt": "2026-05-07T05:00:00Z",
        "lastHeadSha": HEAD_SHA,
    }
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["comments"]["newIssueComments"] == 0
    assert "issue_comments" not in payload["summary"]["actionable"]


def test_bot_comment_actionable_first_then_silenced_after_state_persist(cps):
    bot_comment = _comment(99, "verify-openspec[bot]", body="something to address")
    kwargs = _empty_kwargs()
    kwargs["issue_comment_data"] = [bot_comment]
    payload, new_state = cps.compute_payload(**kwargs)
    assert payload["summary"]["comments"]["newIssueComments"] == 1
    assert "issue_comments" in payload["summary"]["actionable"]
    assert 99 in new_state["seenIssueCommentIds"]

    # Second run with the persisted state -> silenced.
    kwargs2 = _empty_kwargs()
    kwargs2["issue_comment_data"] = [bot_comment]
    kwargs2["state"] = new_state
    payload2, _ = cps.compute_payload(**kwargs2)
    assert payload2["summary"]["comments"]["newIssueComments"] == 0


def test_state_round_trip_caps_seen_ids(cps):
    kwargs = _empty_kwargs()
    kwargs["state"] = {"seenIssueCommentIds": list(range(2000))}
    kwargs["issue_comment_data"] = [_comment(2000, "human-dev")]
    _, new_state = cps.compute_payload(**kwargs)
    assert len(new_state["seenIssueCommentIds"]) <= cps.SEEN_ID_CAP
    assert 2000 in new_state["seenIssueCommentIds"]


# ---------------------------------------------------------------------------
# head-SHA pinning of checks
# ---------------------------------------------------------------------------


def test_commit_pinned_checks_are_canonical_when_present(cps):
    kwargs = _empty_kwargs()
    kwargs["pr_check_data"] = [
        # gh pr checks rollup row that is failing — but we should ignore it
        # because commit-pinned data wins.
        {"name": "old-failing", "bucket": "fail", "conclusion": "FAILURE"},
    ]
    kwargs["commit_check_run_data"] = [
        {"name": "lint", "status": "completed", "conclusion": "success"},
        {"name": "build", "status": "in_progress", "conclusion": None},
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["checks"]["source"] == "commit-pinned"
    assert payload["summary"]["checks"]["failed"] == 0
    assert payload["summary"]["checks"]["pending"] == 1
    assert payload["summary"]["checks"]["passed"] == 1
    assert "failed_checks" not in payload["summary"]["actionable"]


def test_falls_back_to_pr_checks_when_commit_pinned_unavailable(cps):
    kwargs = _empty_kwargs()
    kwargs["pr_check_data"] = [
        {"name": "lint", "bucket": "fail", "conclusion": "FAILURE"},
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["checks"]["source"] == "pr-checks"
    assert payload["summary"]["checks"]["failed"] == 1
    assert "failed_checks" in payload["summary"]["actionable"]


def test_combined_status_entries_are_normalized(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_status_data"] = {
        "statuses": [
            {"context": "ci/legacy", "state": "failure"},
            {"context": "ci/extra", "state": "success"},
        ]
    }
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["checks"]["failed"] == 1
    assert payload["summary"]["checks"]["passed"] == 1


# ---------------------------------------------------------------------------
# effectiveDecision derivation
# ---------------------------------------------------------------------------


def test_effective_decision_later_approved_supersedes_earlier_changes_requested(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [
        _review(1, "alice", "CHANGES_REQUESTED", submitted="2026-05-07T00:00:00Z"),
        _review(2, "alice", "APPROVED", submitted="2026-05-07T05:00:00Z"),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["reviews"]["effectiveDecision"] == "APPROVED"
    assert "changes_requested" not in payload["summary"]["actionable"]


def test_effective_decision_one_reviewer_changes_requested_blocks(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [
        _review(1, "alice", "APPROVED", submitted="2026-05-07T00:00:00Z"),
        _review(2, "bob", "CHANGES_REQUESTED", submitted="2026-05-07T01:00:00Z"),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["reviews"]["effectiveDecision"] == "CHANGES_REQUESTED"
    assert "changes_requested" in payload["summary"]["actionable"]


def test_effective_decision_no_decision_reviews_yields_review_required(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [_review(1, "alice", "COMMENTED")]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["reviews"]["effectiveDecision"] == "REVIEW_REQUIRED"


# ---------------------------------------------------------------------------
# verifyOpenspec runState matrix
# ---------------------------------------------------------------------------


def test_verify_openspec_runstate_none_when_no_label_no_review(cps):
    payload, _ = cps.compute_payload(**_empty_kwargs())
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "none"
    # Opt-in is required: an empty green PR does not request verification.
    assert vo["requiresOpenspecVerification"] is False


def test_verify_openspec_runstate_pending_pickup_when_label_present(cps):
    kwargs = _empty_kwargs()
    kwargs["event_data"] = [_label_event("labeled", "2026-05-07T01:00:00Z")]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "pending-pickup"
    assert vo["requiresOpenspecVerification"] is False


def test_verify_openspec_runstate_in_progress_after_workflow_removes_label(cps):
    """Label removed by workflow but no review submitted yet -> in-progress."""

    kwargs = _empty_kwargs()
    kwargs["event_data"] = [
        _label_event("labeled", "2026-05-07T01:00:00Z"),
        _label_event("unlabeled", "2026-05-07T01:00:30Z"),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    # critical: do NOT report `none` just because pr.labels no longer has it
    assert vo["runState"] == "in-progress"
    assert vo["requiresOpenspecVerification"] is False


def test_verify_openspec_runstate_approved(cps):
    kwargs = _empty_kwargs()
    kwargs["event_data"] = [
        _label_event("labeled", "2026-05-07T01:00:00Z"),
        _label_event("unlabeled", "2026-05-07T01:00:30Z"),
    ]
    kwargs["review_data"] = [_verify_review(7, "APPROVED")]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "approved"
    assert vo["requiresOpenspecVerification"] is False
    assert vo["lastApprovalHeadSha"] == HEAD_SHA


def test_verify_openspec_runstate_approved_does_not_go_stale(cps):
    """Approval exists but for an older commit; still reported as approved."""

    kwargs = _empty_kwargs()
    kwargs["review_data"] = [
        _verify_review(7, "APPROVED", commit_id=OLD_SHA, submitted="2026-05-06T00:00:00Z"),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "approved"
    assert vo["requiresOpenspecVerification"] is False


def test_verify_openspec_runstate_changes_requested(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [_verify_review(7, "CHANGES_REQUESTED")]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "changes-requested"
    assert vo["requiresOpenspecVerification"] is False


def test_verify_openspec_ignores_unrelated_github_actions_reviews(cps):
    """A review from github-actions[bot] WITHOUT the verify report body must
    not count as a verify-openspec approval. Verify-openspec runs as
    github-actions[bot] (the workflow's GITHUB_TOKEN identity) — content is
    what distinguishes verify reviews from any other workflow's reviews."""

    kwargs = _empty_kwargs()
    kwargs["commit_check_run_data"] = [_check_run("Unit", "success")]
    kwargs["review_data"] = [
        _review(
            7,
            "github-actions[bot]",
            "APPROVED",
            commit_id=HEAD_SHA,
            submitted="2026-05-07T01:05:00Z",
            body="LGTM from some-other-workflow",
        ),
    ]
    payload, _ = cps.compute_payload(
        **kwargs,
        openspec_change="add-widget",
        verify_workflow_present=True,
    )
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "none"
    assert vo["requiresOpenspecVerification"] is True


def test_verify_openspec_recognizes_review_by_body_marker(cps):
    """Even if the verification report wording changes slightly, the
    'OpenSpec verify' substring should be enough to identify it."""

    kwargs = _empty_kwargs()
    kwargs["review_data"] = [
        _review(
            7,
            "github-actions[bot]",
            "APPROVED",
            commit_id=HEAD_SHA,
            submitted="2026-05-07T01:05:00Z",
            body="Generated by OpenSpec verify (some new variant)",
        ),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "approved"
    assert vo["requiresOpenspecVerification"] is False


def test_verify_openspec_relabel_after_approval_resets_to_pending(cps):
    """If a label is re-applied AFTER an approval for the same head, runState
    resets to pending-pickup (i.e. workflow has been re-requested)."""

    kwargs = _empty_kwargs()
    kwargs["event_data"] = [
        _label_event("labeled", "2026-05-07T01:00:00Z"),
        _label_event("unlabeled", "2026-05-07T01:00:30Z"),
        _label_event("labeled", "2026-05-07T02:00:00Z"),
    ]
    kwargs["review_data"] = [_verify_review(7, "APPROVED")]
    payload, _ = cps.compute_payload(**kwargs)
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "pending-pickup"
    assert vo["requiresOpenspecVerification"] is False


# ---------------------------------------------------------------------------
# Threads: distinguishing new vs. pending-fix
# ---------------------------------------------------------------------------


def test_unresolved_new_thread_is_actionable_first_time(cps):
    thread = _thread(
        "thread1",
        [_thread_comment("c1node", 555, "human-dev")],
    )
    kwargs = _empty_kwargs()
    kwargs["thread_data"] = [thread]
    payload, new_state = cps.compute_payload(**kwargs)
    threads = payload["summary"]["threads"]
    assert threads["unresolved"] == 1
    assert threads["unresolvedNew"] == 1
    assert "unresolved_review_threads" in payload["summary"]["actionable"]
    assert "thread1" not in new_state["seenReviewThreadIds"]


def test_known_unresolved_thread_keeps_firing_until_resolved(cps):
    thread = _thread(
        "thread1",
        [_thread_comment("c1node", 555, "human-dev")],
    )
    kwargs = _empty_kwargs()
    kwargs["thread_data"] = [thread]
    kwargs["head_sha_override"] = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    kwargs["state"] = {
        "seenReviewThreadIds": ["thread1"],
        "lastHeadSha": HEAD_SHA,
        "lastPolledAt": "2026-05-07T05:00:00Z",
    }
    payload, new_state = cps.compute_payload(**kwargs)
    threads = payload["summary"]["threads"]
    assert threads["unresolved"] == 1
    assert threads["unresolvedNew"] == 1
    assert "unresolved_review_threads" in payload["summary"]["actionable"]
    assert "thread1" not in new_state["seenReviewThreadIds"]


def test_unseen_comment_older_than_watermark_is_still_new(cps):
    now = datetime.now(timezone.utc)
    created = (now - timedelta(minutes=10)).strftime("%Y-%m-%dT%H:%M:%SZ")
    last_polled = (now - timedelta(minutes=5)).strftime("%Y-%m-%dT%H:%M:%SZ")
    kwargs = _empty_kwargs()
    kwargs["issue_comment_data"] = [_comment(9, "human-dev", created=created)]
    kwargs["state"] = {"lastPolledAt": last_polled, "seenIssueCommentIds": []}
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["comments"]["newIssueComments"] == 1
    assert "issue_comments" in payload["summary"]["actionable"]


def test_explicit_since_hides_an_unseen_older_comment(cps):
    kwargs = _empty_kwargs()
    kwargs["issue_comment_data"] = [_comment(9, "human-dev", created="2026-05-07T01:00:00Z")]
    payload, _ = cps.compute_payload(**kwargs, since_override="2026-05-07T05:00:00Z")
    assert payload["summary"]["comments"]["newIssueComments"] == 0


def test_verify_approval_for_another_change_does_not_count(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [_verify_review(7, "APPROVED")]
    payload, _ = cps.compute_payload(**kwargs, openspec_change="add-widget")
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "none"
    assert vo["lastApprovalAt"] is None


def test_verify_approval_matches_the_requested_change(cps):
    kwargs = _empty_kwargs()
    review = _verify_review(7, "APPROVED")
    review["body"] = review["body"].replace("`some-change`", "`add-widget`")
    kwargs["review_data"] = [review]
    payload, _ = cps.compute_payload(**kwargs, openspec_change="add-widget")
    assert payload["summary"]["reviews"]["verifyOpenspec"]["runState"] == "approved"


def test_consumed_label_for_another_change_does_not_block_this_one(cps):
    kwargs = _empty_kwargs()
    kwargs["event_data"] = [
        _label_event("labeled", "2026-05-07T01:00:00Z"),
        _label_event("unlabeled", "2026-05-07T01:00:30Z"),
    ]
    kwargs["review_data"] = [_verify_review(7, "APPROVED", submitted="2026-05-07T01:01:00Z")]
    kwargs["commit_check_run_data"] = [_check_run("Unit", "success")]
    payload, _ = cps.compute_payload(
        **kwargs,
        openspec_change="add-widget",
        verify_workflow_present=True,
    )
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["runState"] == "none"
    assert vo["requiresOpenspecVerification"] is True


def test_in_progress_label_without_a_report_stays_in_progress(cps):
    kwargs = _empty_kwargs()
    kwargs["event_data"] = [
        _label_event("labeled", "2026-05-07T01:00:00Z"),
        _label_event("unlabeled", "2026-05-07T01:00:30Z"),
    ]
    payload, _ = cps.compute_payload(**kwargs, openspec_change="add-widget")
    assert payload["summary"]["reviews"]["verifyOpenspec"]["runState"] == "in-progress"


def test_resolved_thread_reply_is_not_a_standalone_review_comment(cps):
    thread = _thread(
        "thread1",
        [_thread_comment("c1", 555, "human-dev")],
        resolved=True,
    )
    kwargs = _empty_kwargs()
    kwargs["thread_data"] = [thread]
    kwargs["review_comment_data"] = [_review_comment(555, "human-dev", body="addressed in abc")]
    payload, _ = cps.compute_payload(**kwargs)
    assert "review_comments" not in payload["summary"]["actionable"]
    assert "unresolved_review_threads" not in payload["summary"]["actionable"]
    assert payload["summary"]["hasActionable"] is False


def test_standalone_review_comment_stays_actionable(cps):
    kwargs = _empty_kwargs()
    kwargs["review_comment_data"] = [_review_comment(10, "human-dev")]
    payload, _ = cps.compute_payload(**kwargs)
    assert "review_comments" in payload["summary"]["actionable"]


def test_lone_pending_acceptance_does_not_request_verify(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_status_data"] = {
        "statuses": [
            _status(
                "buildkite/terraform-provider-ec-acceptance",
                "pending",
                "https://bk/acc",
            )
        ]
    }
    payload, _ = cps.compute_payload(
        **kwargs,
        openspec_change="add-widget",
        verify_workflow_present=True,
    )
    assert payload["summary"]["checks"]["total"] == 1
    assert (
        payload["summary"]["reviews"]["verifyOpenspec"]["requiresOpenspecVerification"]
        is False
    )


def test_required_fetches_propagate_gh_failure(cps, monkeypatch):
    def boom(*_args, **kwargs):
        if kwargs.get("allow_failure"):
            return kwargs.get("default")
        raise cps.TransientGhError("github unavailable")

    monkeypatch.setattr(cps, "gh_json", boom)
    with pytest.raises(cps.TransientGhError):
        cps.commit_check_runs("o", "r", "abc")
    with pytest.raises(cps.TransientGhError):
        cps.commit_combined_status("o", "r", "abc")
    with pytest.raises(cps.TransientGhError):
        cps.issue_comments("o", "r", 1)
    with pytest.raises(cps.TransientGhError):
        cps.review_comments("o", "r", 1)
    with pytest.raises(cps.TransientGhError):
        cps.reviews("o", "r", 1)
    with pytest.raises(cps.TransientGhError):
        cps.issue_events("o", "r", 1)
    with pytest.raises(cps.TransientGhError):
        cps.review_threads("o", "r", 1)
    assert cps.pr_checks("1") == []


# ---------------------------------------------------------------------------
# Merge-state blocked semantics (BLOCKED is normal during CI; only actionable on transition)
# ---------------------------------------------------------------------------


def test_blocked_without_prior_state_not_actionable(cps):
    """BLOCKED (pending CI) on first poll should not be actionable."""
    kwargs = _empty_kwargs()
    kwargs["pr"] = _pr(mergeStateStatus="BLOCKED")
    payload, new_state = cps.compute_payload(**kwargs)
    assert "merge_or_branch_state" not in payload["summary"]["actionable"]
    assert payload["summary"]["hasActionable"] is False
    assert new_state["lastMergeStateStatus"] == "BLOCKED"


def test_blocked_with_prior_blocked_not_actionable(cps):
    """Steady-state BLOCKED should remain non-actionable across polls."""
    kwargs = _empty_kwargs()
    kwargs["pr"] = _pr(mergeStateStatus="BLOCKED")
    kwargs["state"] = {"lastMergeStateStatus": "BLOCKED"}
    payload, new_state = cps.compute_payload(**kwargs)
    assert "merge_or_branch_state" not in payload["summary"]["actionable"]
    assert payload["summary"]["hasActionable"] is False
    assert new_state["lastMergeStateStatus"] == "BLOCKED"


def test_blocked_transition_from_clean_is_actionable(cps):
    """A fresh transition into BLOCKED (e.g. new push) should be actionable once."""
    kwargs = _empty_kwargs()
    kwargs["pr"] = _pr(mergeStateStatus="BLOCKED")
    kwargs["state"] = {"lastMergeStateStatus": "CLEAN"}
    payload, new_state = cps.compute_payload(**kwargs)
    assert "merge_or_branch_state" in payload["summary"]["actionable"]
    assert payload["summary"]["hasActionable"] is True
    assert new_state["lastMergeStateStatus"] == "BLOCKED"


@pytest.mark.parametrize("bad_state", ["BEHIND", "UNKNOWN", "UNSTABLE"])
def test_non_blocked_bad_merge_state_always_actionable(cps, bad_state):
    """BEHIND, UNKNOWN, and UNSTABLE are always actionable even without prior state."""
    kwargs = _empty_kwargs()
    kwargs["pr"] = _pr(mergeStateStatus=bad_state)
    payload, new_state = cps.compute_payload(**kwargs)
    assert "merge_or_branch_state" in payload["summary"]["actionable"]
    assert payload["summary"]["hasActionable"] is True
    assert new_state["lastMergeStateStatus"] == bad_state


def test_merge_conflicts_always_actionable_regardless_of_merge_state(cps):
    """Actual merge conflicts should always be actionable, even if mergeStateStatus is BLOCKED."""
    kwargs = _empty_kwargs()
    kwargs["pr"] = _pr(mergeStateStatus="BLOCKED")
    kwargs["merge_conflict_data"] = {"hasConflicts": True, "files": ["a.go"], "analysisAvailable": True}
    payload, new_state = cps.compute_payload(**kwargs)
    assert "merge_conflicts" in payload["summary"]["actionable"]
    assert "merge_or_branch_state" not in payload["summary"]["actionable"]
    assert payload["summary"]["hasActionable"] is True
    assert new_state["lastMergeStateStatus"] == "BLOCKED"


# ---------------------------------------------------------------------------
# Resilience
# ---------------------------------------------------------------------------


def test_main_emits_transient_exit_when_pr_view_returns_empty(cps, monkeypatch, capsys):
    monkeypatch.setattr(cps, "pr_view", lambda _: {})
    monkeypatch.setattr(cps, "repo_info", lambda: {"owner": "o", "name": "r"})
    rc = cps.main(["999"])
    assert rc == cps.EXIT_TRANSIENT
    out = capsys.readouterr().out
    body = json.loads(out)
    assert body.get("transient") is True


def test_main_emits_transient_exit_when_gh_repeatedly_fails(cps, monkeypatch, capsys):
    def failing(_args, *, default=None, allow_failure=False, retries=1):
        raise cps.TransientGhError(json.dumps({"error": "boom", "transient": True}))

    monkeypatch.setattr(cps, "gh_json", failing)
    rc = cps.main(["999"])
    assert rc == cps.EXIT_TRANSIENT
    out = capsys.readouterr().out
    body = json.loads(out)
    assert body.get("transient") is True


# ---------------------------------------------------------------------------
# State file round-trip via filesystem
# ---------------------------------------------------------------------------


def test_state_file_roundtrip(cps, tmp_path):
    p = tmp_path / "state.json"
    cps.save_state(str(p), {"pr": 1, "seenIssueCommentIds": [1, 2, 3]})
    loaded = cps.load_state(str(p))
    assert loaded["pr"] == 1
    assert loaded["seenIssueCommentIds"] == [1, 2, 3]


def test_state_file_load_missing_returns_empty(cps, tmp_path):
    p = tmp_path / "does-not-exist.json"
    assert cps.load_state(str(p)) == {}


def test_state_file_load_corrupt_returns_empty(cps, tmp_path):
    p = tmp_path / "corrupt.json"
    p.write_text("not json {")
    assert cps.load_state(str(p)) == {}


# ---------------------------------------------------------------------------
# Sanity on exposed thread comment ids (REST + GraphQL)
# ---------------------------------------------------------------------------


def test_review_threads_query_requests_database_id(cps):
    """The GraphQL query string must request both `id` and `databaseId` so
    workers can call REST in_reply_to (databaseId) AND resolveReviewThread
    (node id)."""

    src = SCRIPT.read_text()
    assert "databaseId" in src


# ---------------------------------------------------------------------------
# Cloud provider CI split
# ---------------------------------------------------------------------------


def _status(context, state, url="https://status.example/1"):
    return {"context": context, "state": state, "target_url": url}


def _check_run(name, conclusion, url="https://runs.example/1", status="completed"):
    return {
        "name": name,
        "status": status,
        "conclusion": conclusion,
        "html_url": url,
    }


def test_required_passed_needs_unit_and_cla(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_check_run_data"] = [_check_run("Unit", "success")]
    kwargs["commit_status_data"] = {
        "statuses": [
            _status("buildkite/terraform-provider-ec-acceptance", "success", "https://bk/acc")
        ]
    }
    missing_cla, _ = cps.compute_payload(**kwargs)
    checks = missing_cla["summary"]["checks"]
    assert checks["passedNames"] == ["Unit"]
    assert checks["requiredPassed"] is False
    assert cps.format_focused(missing_cla)["checks"]["requiredPassed"] is False

    kwargs["commit_status_data"]["statuses"].append(_status("CLA", "success", "https://cla"))
    both, _ = cps.compute_payload(**kwargs)
    assert both["summary"]["checks"]["requiredPassed"] is True
    assert "CLA" in both["summary"]["checks"]["passedNames"]


def test_head_sha_override_pins_commit_fetches(cps, monkeypatch):
    seen = {}

    monkeypatch.setattr(cps, "repo_info", lambda: {"owner": "o", "name": "r"})
    monkeypatch.setattr(
        cps,
        "pr_view",
        lambda _pr: {"number": 1, "headRefOid": "current-head", "baseRefName": "master"},
    )
    monkeypatch.setattr(cps, "pr_checks", lambda _pr: [])
    monkeypatch.setattr(cps, "issue_comments", lambda *_args: [])
    monkeypatch.setattr(cps, "review_comments", lambda *_args: [])
    monkeypatch.setattr(cps, "reviews", lambda *_args: [])
    monkeypatch.setattr(cps, "review_threads", lambda *_args: [])
    monkeypatch.setattr(cps, "issue_events", lambda *_args: [])
    monkeypatch.setattr(cps, "merge_conflicts", lambda _pr: {})

    def runs(_owner, _repo, sha):
        seen["runs"] = sha
        return []

    def status(_owner, _repo, sha):
        seen["status"] = sha
        return {}

    monkeypatch.setattr(cps, "commit_check_runs", runs)
    monkeypatch.setattr(cps, "commit_combined_status", status)
    cps.fetch_all("1", "older-sha")
    assert seen == {"runs": "older-sha", "status": "older-sha"}


def test_fetch_retries_once_when_the_head_moves(cps, monkeypatch):
    views = iter(
        [
            {"number": 1, "headRefOid": "sha-a"},
            {"number": 1, "headRefOid": "sha-b"},
            {"number": 1, "headRefOid": "sha-b"},
            {"number": 1, "headRefOid": "sha-b"},
        ]
    )
    pinned: list[str] = []

    monkeypatch.setattr(cps, "repo_info", lambda: {"owner": "o", "name": "r"})
    monkeypatch.setattr(cps, "pr_view", lambda _pr: next(views))
    monkeypatch.setattr(cps, "pr_checks", lambda _pr: [])
    monkeypatch.setattr(cps, "issue_comments", lambda *_args: [])
    monkeypatch.setattr(cps, "review_comments", lambda *_args: [])
    monkeypatch.setattr(cps, "reviews", lambda *_args: [])
    monkeypatch.setattr(cps, "review_threads", lambda *_args: [])
    monkeypatch.setattr(cps, "issue_events", lambda *_args: [])
    monkeypatch.setattr(cps, "merge_conflicts", lambda _pr: {})
    monkeypatch.setattr(
        cps, "commit_check_runs", lambda _o, _r, sha: pinned.append(sha) or []
    )
    monkeypatch.setattr(cps, "commit_combined_status", lambda _o, _r, sha: {})

    raw = cps.fetch_all("1")
    assert raw["pr"]["headRefOid"] == "sha-b"
    assert pinned == ["sha-a", "sha-b"]


def test_fetch_is_transient_when_the_head_keeps_moving(cps, monkeypatch):
    views = iter(
        [
            {"number": 1, "headRefOid": "sha-a"},
            {"number": 1, "headRefOid": "sha-b"},
            {"number": 1, "headRefOid": "sha-b"},
            {"number": 1, "headRefOid": "sha-c"},
        ]
    )
    monkeypatch.setattr(cps, "repo_info", lambda: {"owner": "o", "name": "r"})
    monkeypatch.setattr(cps, "pr_view", lambda _pr: next(views))
    monkeypatch.setattr(cps, "pr_checks", lambda _pr: [])
    monkeypatch.setattr(cps, "issue_comments", lambda *_args: [])
    monkeypatch.setattr(cps, "review_comments", lambda *_args: [])
    monkeypatch.setattr(cps, "reviews", lambda *_args: [])
    monkeypatch.setattr(cps, "review_threads", lambda *_args: [])
    monkeypatch.setattr(cps, "issue_events", lambda *_args: [])
    monkeypatch.setattr(cps, "merge_conflicts", lambda _pr: {})
    monkeypatch.setattr(cps, "commit_check_runs", lambda *_args: [])
    monkeypatch.setattr(cps, "commit_combined_status", lambda *_args: {})

    with pytest.raises(cps.TransientGhError, match="pr head changed during fetch"):
        cps.fetch_all("1")


def test_matching_head_uses_the_fresh_pr_metadata(cps, monkeypatch):
    views = iter(
        [
            {"number": 1, "headRefOid": "sha-a", "state": "OPEN", "isDraft": False, "mergeStateStatus": "CLEAN"},
            {
                "number": 1,
                "headRefOid": "sha-a",
                "state": "CLOSED",
                "isDraft": True,
                "mergeStateStatus": "DIRTY",
            },
        ]
    )
    monkeypatch.setattr(cps, "repo_info", lambda: {"owner": "o", "name": "r"})
    monkeypatch.setattr(cps, "pr_view", lambda _pr: next(views))
    monkeypatch.setattr(cps, "pr_checks", lambda _pr: [])
    monkeypatch.setattr(cps, "issue_comments", lambda *_args: [])
    monkeypatch.setattr(cps, "review_comments", lambda *_args: [])
    monkeypatch.setattr(cps, "reviews", lambda *_args: [])
    monkeypatch.setattr(cps, "review_threads", lambda *_args: [])
    monkeypatch.setattr(cps, "issue_events", lambda *_args: [])
    monkeypatch.setattr(cps, "merge_conflicts", lambda _pr: {})
    monkeypatch.setattr(cps, "commit_check_runs", lambda *_args: [])
    monkeypatch.setattr(cps, "commit_combined_status", lambda *_args: {})

    raw = cps.fetch_all("1")
    assert raw["pr"]["state"] == "CLOSED"
    assert raw["pr"]["isDraft"] is True
    assert raw["pr"]["headRefOid"] == "sha-a"
    assert raw["pr"]["mergeStateStatus"] == "CLEAN"


def test_head_sha_override_does_not_borrow_current_head_checks(cps):
    kwargs = _empty_kwargs()
    kwargs["pr_check_data"] = [{"name": "Unit", "state": "SUCCESS", "bucket": "pass"}]
    payload, _ = cps.compute_payload(**kwargs, head_sha_override="older-sha")
    checks = payload["summary"]["checks"]
    assert checks["source"] == "commit-pinned"
    assert checks["headSha"] == "older-sha"
    assert checks["passed"] == 0
    assert checks["requiredPassed"] is False


def test_review_thread_comments_past_the_first_page_are_kept(cps, monkeypatch):
    first_page = [{"id": f"n{i}", "databaseId": i} for i in range(50)]

    def fake_gh_json(args, **_kwargs):
        query = " ".join(args)
        if "reviewThreads" in query:
            return {
                "data": {
                    "repository": {
                        "pullRequest": {
                            "reviewThreads": {
                                "pageInfo": {"hasNextPage": False},
                                "nodes": [
                                    {
                                        "id": "T1",
                                        "isResolved": True,
                                        "isOutdated": False,
                                        "comments": {
                                            "pageInfo": {
                                                "hasNextPage": True,
                                                "endCursor": "c1",
                                            },
                                            "nodes": first_page,
                                        },
                                    }
                                ],
                            }
                        }
                    }
                }
            }
        return {
            "data": {
                "node": {
                    "comments": {
                        "pageInfo": {"hasNextPage": False, "endCursor": None},
                        "nodes": [{"id": "n50", "databaseId": 50, "body": "later reply"}],
                    }
                }
            }
        }

    monkeypatch.setattr(cps, "gh_json", fake_gh_json)
    threads = cps.review_threads("o", "r", 1)
    nodes = threads[0]["comments"]["nodes"]
    assert len(nodes) == 51
    assert nodes[-1]["body"] == "later reply"


def test_combined_status_context_is_the_check_name(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_status_data"] = {
        "statuses": [_status("ci/legacy", "failure", "https://ci/legacy")]
    }
    payload, _ = cps.compute_payload(**kwargs)
    failed = payload["summary"]["checks"]["failedChecks"]
    assert failed == [{"name": "ci/legacy", "url": "https://ci/legacy", "class": "unknown"}]
    assert "failed_checks" in payload["summary"]["actionable"]


def test_unit_failure_is_autofixable(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_check_run_data"] = [
        _check_run("Unit", "failure", "https://gha/unit"),
    ]
    payload, _ = cps.compute_payload(**kwargs)
    checks = payload["summary"]["checks"]
    assert checks["failed"] == 1
    assert checks["failedNames"] == ["Unit"]
    assert checks["failedChecks"] == [
        {"name": "Unit", "url": "https://gha/unit", "class": "auto-fixable"}
    ]
    assert payload["summary"]["actionable"] == ["failed_checks"]


def test_acceptance_failure_is_out_of_band(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_check_run_data"] = [
        _check_run("Unit", "success", "https://gha/unit"),
    ]
    kwargs["commit_status_data"] = {
        "statuses": [
            _status(
                "buildkite/terraform-provider-ec-acceptance",
                "failure",
                "https://bk/acc",
            )
        ]
    }
    payload, _ = cps.compute_payload(**kwargs)
    checks = payload["summary"]["checks"]
    assert checks["failed"] == 0
    assert checks["passed"] == 1
    assert checks["total"] == 2
    assert checks["failedNames"] == []
    assert checks["failedChecks"] == [
        {
            "name": "buildkite/terraform-provider-ec-acceptance",
            "url": "https://bk/acc",
            "class": "out-of-band",
        }
    ]
    assert checks["outOfBand"] == [
        {
            "name": "buildkite/terraform-provider-ec-acceptance",
            "state": "failed",
            "url": "https://bk/acc",
        }
    ]
    assert "failed_checks" not in payload["summary"]["actionable"]
    assert "acceptance_failed" in payload["summary"]["actionable"]


def test_acceptance_pending_does_not_block_verify(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_check_run_data"] = [
        _check_run("Unit", "success"),
        _check_run("Validate OpenSpecs", "success", "https://gha/openspec"),
    ]
    kwargs["commit_status_data"] = {
        "statuses": [
            _status(
                "buildkite/terraform-provider-ec-acceptance",
                "pending",
                "https://bk/acc",
            )
        ]
    }
    payload, _ = cps.compute_payload(
        **kwargs,
        openspec_change="add-widget",
        verify_workflow_present=True,
    )
    checks = payload["summary"]["checks"]
    assert checks["pending"] == 0
    assert checks["outOfBand"][0]["state"] == "pending"
    assert payload["summary"]["actionable"] == []
    assert payload["summary"]["hasActionable"] is False
    vo = payload["summary"]["reviews"]["verifyOpenspec"]
    assert vo["requiresOpenspecVerification"] is True


def test_acceptance_failure_blocks_verify_until_green(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_status_data"] = {
        "statuses": [
            _status("buildkite/terraform-provider-ec-acceptance", "failure"),
        ]
    }
    payload, _ = cps.compute_payload(
        **kwargs,
        openspec_change="add-widget",
        verify_workflow_present=True,
    )
    assert payload["summary"]["reviews"]["verifyOpenspec"]["requiresOpenspecVerification"] is False


def test_cla_failure_is_unknown_and_not_autofixable_class(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_status_data"] = {
        "statuses": [_status("CLA", "failure", "https://cla/1")]
    }
    payload, _ = cps.compute_payload(**kwargs)
    checks = payload["summary"]["checks"]
    assert checks["failed"] == 1
    assert checks["failedChecks"] == [
        {"name": "CLA", "url": "https://cla/1", "class": "unknown"}
    ]
    assert payload["summary"]["actionable"] == ["failed_checks"]
    assert "acceptance_failed" not in payload["summary"]["actionable"]


def test_release_failure_escalates_like_acceptance(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_status_data"] = {
        "statuses": [
            _status(
                "buildkite/terraform-provider-ec-release",
                "failure",
                "https://bk/rel",
            )
        ]
    }
    payload, _ = cps.compute_payload(**kwargs)
    checks = payload["summary"]["checks"]
    assert checks["failed"] == 0
    assert checks["outOfBand"] == [
        {
            "name": "buildkite/terraform-provider-ec-release",
            "state": "failed",
            "url": "https://bk/rel",
        }
    ]
    assert payload["summary"]["actionable"] == ["acceptance_failed"]


def test_skipped_out_of_band_check_is_actionable(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_status_data"] = {
        "statuses": [
            _status("buildkite/terraform-provider-ec-acceptance", "success"),
        ]
    }
    kwargs["commit_check_run_data"] = [
        _check_run(
            "buildkite/terraform-provider-ec-release",
            "neutral",
            "https://bk/rel",
        )
    ]
    payload, _ = cps.compute_payload(**kwargs)
    states = {item["name"]: item["state"] for item in payload["summary"]["checks"]["outOfBand"]}
    assert states["buildkite/terraform-provider-ec-acceptance"] == "passed"
    assert states["buildkite/terraform-provider-ec-release"] == "skipped"
    assert payload["summary"]["actionable"] == ["acceptance_failed"]
    assert payload["summary"]["checks"]["failed"] == 0


def test_skipped_approve_on_pr_checks_fallback_is_not_a_failure(cps):
    kwargs = _empty_kwargs()
    kwargs["pr_check_data"] = [
        {"name": "Approve", "bucket": "skipping", "conclusion": "SKIPPED"},
    ]
    payload, _ = cps.compute_payload(**kwargs)
    checks = payload["summary"]["checks"]
    assert checks["source"] == "pr-checks"
    assert checks["failed"] == 0
    assert checks["total"] == 1
    assert checks["failedChecks"] == []
    assert "failed_checks" not in payload["summary"]["actionable"]


def test_pending_unit_blocks_verify_when_opted_in(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_check_run_data"] = [
        _check_run("Unit", None, status="in_progress"),
    ]
    payload, _ = cps.compute_payload(
        **kwargs,
        openspec_change="add-widget",
        verify_workflow_present=True,
    )
    assert payload["summary"]["checks"]["pending"] == 1
    assert payload["summary"]["reviews"]["verifyOpenspec"]["requiresOpenspecVerification"] is False


def test_verify_requires_change_workflow_and_visible_checks(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_check_run_data"] = [_check_run("Unit", "success")]
    missing_change, _ = cps.compute_payload(**kwargs, verify_workflow_present=True)
    missing_workflow, _ = cps.compute_payload(**kwargs, openspec_change="add-widget")
    blank_change, _ = cps.compute_payload(
        **kwargs,
        openspec_change="  ",
        verify_workflow_present=True,
    )
    no_checks, _ = cps.compute_payload(
        **_empty_kwargs(),
        openspec_change="add-widget",
        verify_workflow_present=True,
    )
    ready, _ = cps.compute_payload(
        **kwargs,
        openspec_change="add-widget",
        verify_workflow_present=True,
    )
    assert missing_change["summary"]["reviews"]["verifyOpenspec"]["requiresOpenspecVerification"] is False
    assert missing_workflow["summary"]["reviews"]["verifyOpenspec"]["requiresOpenspecVerification"] is False
    assert blank_change["summary"]["reviews"]["verifyOpenspec"]["requiresOpenspecVerification"] is False
    assert no_checks["summary"]["reviews"]["verifyOpenspec"]["requiresOpenspecVerification"] is False
    assert ready["summary"]["reviews"]["verifyOpenspec"]["requiresOpenspecVerification"] is True


def test_pr_checks_fallback_uses_bucket_and_link(cps):
    """`gh pr checks --json` has no conclusion or detailsUrl. Bucket and link are enough."""

    kwargs = _empty_kwargs()
    kwargs["pr_check_data"] = [
        {
            "name": "Unit",
            "bucket": "fail",
            "state": "FAILURE",
            "link": "https://gha/unit",
        }
    ]
    payload, _ = cps.compute_payload(**kwargs)
    checks = payload["summary"]["checks"]
    assert checks["source"] == "pr-checks"
    assert checks["failedChecks"] == [
        {"name": "Unit", "url": "https://gha/unit", "class": "auto-fixable"}
    ]
    assert payload["summary"]["actionable"] == ["failed_checks"]


def test_detect_verify_workflow_globs_and_env_override(cps, tmp_path, monkeypatch):
    monkeypatch.delenv("CHECK_PR_STATE_VERIFY_WORKFLOW", raising=False)
    assert cps.detect_verify_workflow(root=str(tmp_path)) is False
    workflows = tmp_path / ".github" / "workflows"
    workflows.mkdir(parents=True)
    (workflows / "openspec-verify-label.lock.yml").write_text("name: verify\n")
    assert cps.detect_verify_workflow(root=str(tmp_path)) is True
    monkeypatch.setenv("CHECK_PR_STATE_VERIFY_WORKFLOW", "0")
    assert cps.detect_verify_workflow(root=str(tmp_path)) is False
    monkeypatch.setenv("CHECK_PR_STATE_VERIFY_WORKFLOW", "1")
    assert cps.detect_verify_workflow(root=str(tmp_path)) is True


def test_two_concatenated_comment_pages_flatten(cps):
    raw = '[{"id": 1, "body": "first"}]\n[{"id": 2, "body": "second"}]'
    parsed = cps.loads_gh_output(raw)
    assert cps.flatten_item_pages(parsed) == [
        {"id": 1, "body": "first"},
        {"id": 2, "body": "second"},
    ]


def test_slurped_comment_pages_flatten(cps):
    raw = '[[{"id": 1}], [{"id": 2}, {"id": 3}]]'
    parsed = cps.loads_gh_output(raw)
    assert cps.flatten_item_pages(parsed) == [{"id": 1}, {"id": 2}, {"id": 3}]


def test_single_comment_page_stays_a_flat_list(cps):
    raw = '[{"id": 1}, {"id": 2}]'
    parsed = cps.loads_gh_output(raw)
    assert cps.flatten_item_pages(parsed) == [{"id": 1}, {"id": 2}]


def test_two_check_run_pages_merge(cps):
    concatenated = (
        '{"check_runs": [{"name": "Unit"}]}\n'
        '{"check_runs": [{"name": "Validate OpenSpecs"}]}'
    )
    slurped = (
        '[{"check_runs": [{"name": "Unit"}]}, '
        '{"check_runs": [{"name": "Validate OpenSpecs"}]}]'
    )
    expected = [{"name": "Unit"}, {"name": "Validate OpenSpecs"}]
    assert cps.check_runs_from_payload(cps.loads_gh_output(concatenated)) == expected
    assert cps.check_runs_from_payload(cps.loads_gh_output(slurped)) == expected


def test_two_combined_status_pages_merge(cps):
    concatenated = (
        '{"state":"pending","statuses":[{"context":"cla"}]}\n'
        '{"state":"pending","statuses":[{"context":"buildkite/terraform-provider-ec-acceptance"}]}'
    )
    merged = cps.combined_status_from_payload(cps.loads_gh_output(concatenated))
    assert [status["context"] for status in merged["statuses"]] == [
        "cla",
        "buildkite/terraform-provider-ec-acceptance",
    ]


def test_merge_tree_stage_line_records_the_path(cps):
    output = "100644 abcdef 1\tsrc/foo.go\nCONFLICT (modify/delete): src/bar.go deleted in ours"
    assert cps.parse_merge_tree_conflicts(output) == ["src/foo.go"]


def test_failed_fetch_falls_back_to_github_mergeability(cps, monkeypatch):
    def fake_run(args, **_kwargs):
        completed = type("Completed", (), {})()
        completed.returncode = 1
        completed.stdout = ""
        completed.stderr = "fetch failed"
        return completed

    monkeypatch.setattr(cps, "run_git", fake_run)
    result = cps.merge_conflicts(
        {
            "number": 1,
            "baseRefName": "master",
            "mergeable": "CONFLICTING",
            "mergeStateStatus": "DIRTY",
        }
    )
    assert result["source"] == "github-mergeability-fallback"
    assert result["analysisAvailable"] is False
    assert result["hasConflicts"] is True
    assert result["files"] == []


def test_paginated_fetches_do_not_pass_slurp(cps, monkeypatch):
    seen: list[list[str]] = []

    def fake_gh_json(args, **kwargs):
        seen.append(list(args))
        if any("check-runs" in part for part in args):
            return {"check_runs": [{"name": "Unit"}]}
        if any(part.endswith("/status") for part in args):
            return {"statuses": [{"context": "cla"}]}
        return [{"id": 1}]

    monkeypatch.setattr(cps, "gh_json", fake_gh_json)
    assert cps.issue_comments("o", "r", 1) == [{"id": 1}]
    assert cps.review_comments("o", "r", 1) == [{"id": 1}]
    assert cps.reviews("o", "r", 1) == [{"id": 1}]
    assert cps.issue_events("o", "r", 1) == [{"id": 1}]
    assert cps.commit_check_runs("o", "r", "abc") == [{"name": "Unit"}]
    assert cps.commit_combined_status("o", "r", "abc") == {
        "statuses": [{"context": "cla"}]
    }
    assert len(seen) == 6
    for args in seen:
        assert "--paginate" in args
        assert "--slurp" not in args


def test_out_of_band_settled_waits_for_a_terminal_acceptance_status(cps):
    acceptance = "buildkite/terraform-provider-ec-acceptance"
    release = "buildkite/terraform-provider-ec-release"
    assert cps.out_of_band_settled([]) is False
    assert cps.out_of_band_settled([{"name": acceptance, "state": "pending"}]) is False
    assert (
        cps.out_of_band_settled(
            [
                {"name": acceptance, "state": "passed"},
                {"name": release, "state": "pending"},
            ]
        )
        is False
    )
    assert cps.out_of_band_settled([{"name": release, "state": "passed"}]) is False
    assert cps.out_of_band_settled([{"name": acceptance, "state": "failed"}]) is True
    assert (
        cps.out_of_band_settled(
            [
                {"name": acceptance, "state": "passed"},
                {"name": release, "state": "passed"},
            ]
        )
        is True
    )


def test_watch_acceptance_defaults_to_a_slow_long_poll(cps):
    args = cps.parse_args(["42", "--watch-acceptance"])
    cps._resolve_watch_timing(args)
    assert args.interval == cps.ACCEPTANCE_INTERVAL_SECONDS
    assert args.max_duration == cps.ACCEPTANCE_MAX_DURATION_SECONDS
    explicit = cps.parse_args(
        [
            "42",
            "--watch-acceptance",
            "--interval",
            "60",
            "--max-duration",
            "1800",
        ]
    )
    cps._resolve_watch_timing(explicit)
    assert explicit.interval == 60
    assert explicit.max_duration == 1800


def test_watch_flags_are_mutually_exclusive(cps):
    with pytest.raises(SystemExit):
        cps.parse_args(["42", "--watch", "--watch-acceptance"])


def test_watch_exits_on_first_actionable_tick(cps, monkeypatch, capsys):
    def fake_fetch(_pr, _head_sha=None):
        return {"pr": {"number": 42}}

    def fake_compute(**kwargs):
        payload = {
            "summary": {
                "hasActionable": True,
                "actionable": ["failed_checks"],
                "checks": {"outOfBand": []},
                "pr": {"number": 42},
            }
        }
        return payload, {"pr": 42}

    monkeypatch.setattr(cps, "fetch_all", fake_fetch)
    monkeypatch.setattr(cps, "compute_payload", fake_compute)
    monkeypatch.setattr(cps.time, "sleep", lambda _seconds: None)
    rc = cps.main(["42", "--watch", "--no-state", "--interval", "1", "--max-duration", "30"])
    assert rc == cps.EXIT_OK
    lines = [json.loads(line) for line in capsys.readouterr().out.splitlines() if line]
    assert lines[-1]["outcome"] == "actionable"


def test_watch_acceptance_timeout_does_not_save_state(cps, monkeypatch, capsys, tmp_path):
    saves: list[dict] = []

    def fake_fetch(_pr, _head_sha=None):
        return {"pr": {"number": 42}}

    def fake_compute(**kwargs):
        payload = {
            "summary": {
                "hasActionable": False,
                "actionable": [],
                "checks": {
                    "outOfBand": [
                        {
                            "name": "buildkite/terraform-provider-ec-acceptance",
                            "state": "pending",
                            "url": "https://bk/acc",
                        }
                    ]
                },
                "pr": {"number": 42},
            }
        }
        return payload, {"pr": 42}

    monkeypatch.setattr(cps, "fetch_all", fake_fetch)
    monkeypatch.setattr(cps, "compute_payload", fake_compute)
    monkeypatch.setattr(cps, "save_state", lambda path, state: saves.append(state))
    monkeypatch.setattr(cps.time, "sleep", lambda _seconds: None)
    rc = cps.main(
        [
            "42",
            "--watch-acceptance",
            "--state-file",
            str(tmp_path / "state.json"),
            "--interval",
            "1",
            "--max-duration",
            "0",
        ]
    )
    assert rc == cps.EXIT_TIMEOUT
    assert saves == []
    lines = [json.loads(line) for line in capsys.readouterr().out.splitlines() if line]
    assert lines[-1]["outcome"] == "timeout"
    assert lines[-1]["lastTickTransient"] is False
    assert lines[-1]["lastSummary"]["checks"]["outOfBand"][0]["state"] == "pending"


def test_watch_timeout_after_a_transient_tick_is_marked_stale(cps, monkeypatch, capsys):
    def fake_fetch(_pr, _head_sha=None):
        raise cps.TransientGhError('{"error":"down","transient":true}')

    monkeypatch.setattr(cps, "fetch_all", fake_fetch)
    monkeypatch.setattr(cps.time, "sleep", lambda _seconds: None)
    rc = cps.main(
        ["42", "--watch", "--no-state", "--interval", "1", "--max-duration", "0"]
    )
    assert rc == cps.EXIT_TIMEOUT
    lines = [json.loads(line) for line in capsys.readouterr().out.splitlines() if line]
    assert lines[-1]["outcome"] == "timeout"
    assert lines[-1]["lastTickTransient"] is True
    assert lines[-1]["lastSummary"] is None


def test_requested_check_run_is_pending(cps):
    kwargs = _empty_kwargs()
    kwargs["commit_check_run_data"] = [
        _check_run("Validate OpenSpecs", "", status="requested")
    ]
    payload, _ = cps.compute_payload(**kwargs)
    assert payload["summary"]["checks"]["pending"] == 1
    assert payload["summary"]["checks"]["pendingNames"] == ["Validate OpenSpecs"]


def test_commented_review_with_a_body_is_actionable(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [_review(1, "alice", "COMMENTED", body="please rename this")]
    payload, _ = cps.compute_payload(**kwargs)
    assert "commented_reviews" in payload["summary"]["actionable"]
    focused = cps.format_focused(payload)
    assert focused["reviews"]["newReviews"][0]["body"] == "please rename this"


def test_empty_commented_review_is_not_actionable(cps):
    kwargs = _empty_kwargs()
    kwargs["review_data"] = [_review(1, "alice", "COMMENTED", body="  ")]
    payload, _ = cps.compute_payload(**kwargs)
    assert "commented_reviews" not in payload["summary"]["actionable"]


def test_watch_sleep_does_not_overshoot_max_duration(cps, monkeypatch, capsys):
    slept: list[float] = []
    clock = {"t": 0.0}

    def fake_fetch(_pr, _head_sha=None):
        return {"pr": {"number": 42}}

    def fake_compute(**kwargs):
        return {
            "summary": {
                "hasActionable": False,
                "actionable": [],
                "checks": {"outOfBand": []},
                "pr": {"number": 42},
            }
        }, {"pr": 42}

    def fake_sleep(seconds):
        slept.append(seconds)
        clock["t"] += seconds

    monkeypatch.setattr(cps, "fetch_all", fake_fetch)
    monkeypatch.setattr(cps, "compute_payload", fake_compute)
    monkeypatch.setattr(cps.time, "monotonic", lambda: clock["t"])
    monkeypatch.setattr(cps.time, "sleep", fake_sleep)
    rc = cps.main(
        ["42", "--watch", "--no-state", "--interval", "60", "--max-duration", "10"]
    )
    assert rc == cps.EXIT_TIMEOUT
    assert slept == [10]


def test_focused_output_includes_pr_state_and_draft(cps):
    payload, _ = cps.compute_payload(**_empty_kwargs())
    focused = cps.format_focused(payload)
    assert focused["pr"]["state"] == "OPEN"
    assert focused["pr"]["isDraft"] is False


def test_acceptance_watch_keeps_a_stale_thread_reply(cps):
    now = datetime.now(timezone.utc)
    last_polled = (now - timedelta(minutes=150)).strftime("%Y-%m-%dT%H:%M:%SZ")
    replied = (now - timedelta(minutes=5)).strftime("%Y-%m-%dT%H:%M:%SZ")
    thread = _thread(
        "T1",
        [
            _thread_comment("c1", 1, "human-dev", created="2026-05-07T01:00:00Z"),
            _thread_comment("c2", 999, "human-dev", created=replied),
        ],
    )
    thread["comments"]["nodes"][1]["body"] = "follow up"
    kwargs = _empty_kwargs()
    kwargs["thread_data"] = [thread]
    kwargs["review_comment_data"] = [
        _review_comment(999, "human-dev", body="follow up", created=replied)
    ]
    kwargs["state"] = {
        "seenReviewThreadIds": ["T1"],
        "seenReviewCommentIds": [1],
        "lastPolledAt": last_polled,
        "lastHeadSha": HEAD_SHA,
    }
    wiped, _ = cps.compute_payload(**kwargs)
    kept, _ = cps.compute_payload(**kwargs, retain_stale_since=True)
    for payload in (wiped, kept):
        details = cps.format_focused(payload)["threadDetails"]["T1"]["comments"]
        assert any(comment["body"] == "follow up" for comment in details)


def test_watch_acceptance_waits_through_other_actionable_signals(cps, monkeypatch, capsys, tmp_path):
    states = iter(["pending", "failed"])
    saves: list[dict] = []

    def fake_fetch(_pr, _head_sha=None):
        return {"pr": {"number": 42}}

    def fake_compute(**kwargs):
        state = next(states)
        actionable = (
            ["merge_or_branch_state"] if state == "pending" else ["acceptance_failed"]
        )
        payload = {
            "summary": {
                "hasActionable": True,
                "actionable": actionable,
                "checks": {
                    "outOfBand": [
                        {
                            "name": "buildkite/terraform-provider-ec-acceptance",
                            "state": state,
                            "url": "https://bk/acc",
                        }
                    ]
                },
                "pr": {"number": 42},
            }
        }
        return payload, {"pr": 42, "seen": state}

    monkeypatch.setattr(cps, "fetch_all", fake_fetch)
    monkeypatch.setattr(cps, "compute_payload", fake_compute)
    monkeypatch.setattr(cps, "save_state", lambda path, state: saves.append(state))
    monkeypatch.setattr(cps.time, "sleep", lambda _seconds: None)

    rc = cps.main(
        [
            "42",
            "--watch-acceptance",
            "--state-file",
            str(tmp_path / "state.json"),
            "--interval",
            "1",
            "--max-duration",
            "30",
        ]
    )
    assert rc == cps.EXIT_OK
    assert saves == [{"pr": 42, "seen": "failed"}]
    lines = [json.loads(line) for line in capsys.readouterr().out.splitlines() if line]
    assert lines[-1]["outcome"] == "acceptance_settled"
    assert lines[-1]["payload"]["actionable"] == ["acceptance_failed"]
